image: node:14.17.6

pipelines:
  default:

    - step:
        name: Build
        script:
          - cd functions; npm install;
        artifacts:
          - functions/**

    - step:
        name: Deploy to Firebase
        deployment: production
        script:
          - echo $PRICE_ID
          - echo $STRIPE_SK
#          - firebase functions:config:set stripe.price_id="$PRICE_ID" stripe.sk="$STRIPE_SK"
          - pipe: atlassian/firebase-deploy:1.3.0
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN
              PROJECT_ID: $FIREBASE_PROJECT
