image: rossedlin/node:14

pipelines:
  default:

    - step:
        name: Build
        script:
          - cd functions; npm install;
          - firebase functions:config:set stripe.price_id="$PRICE_ID" stripe.sk="$STRIPE_SK"
        artifacts:
          - functions/**

    - step:
        name: Deploy to Firebase
        deployment: production
        script:
          - pipe: atlassian/firebase-deploy:1.3.0
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN
              PROJECT_ID: $FIREBASE_PROJECT
