image: rossedlin/node:14

pipelines:
  default:

    - step:
        name: Build
        script:
          - cd functions; npm install;
          - firebase functions:config:set stripe.test_price="$STRIPE_TEST_PRICE" stripe.test_sk="$STRIPE_TEST_SK" stripe.live_price="$STRIPE_LIVE_PRICE" stripe.live_sk="$STRIPE_LIVE_SK"
        artifacts:
          - functions/**

    - step:
        name: Deploy to Firebase
        deployment: production
        script:
          - pipe: atlassian/firebase-deploy:1.3.0
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN
              PROJECT_ID: $FIREBASE_PROJECT
